### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by fengzeyan** [HuobiGroup/huobi-chain#4]
Centos 7 编译完成后，执行./huobi-chain后报错，报错信息如下：
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'the main future has panicked: Canceled', src/libcore/result.rs:1084:5

**Comment by fengzeyan** [comment]
抱歉，我自己的问题，应该在项目根目录下运行，不能在target/release下面运行。
